### ISSUE TITLE
tomcat/lib vagent加载失败

### ISSUE THREAD

**Issue by keecth** [veo/vagent#11]
测试发现将vagent发在tmcat/lib目录下，利用spi机制加载时，此时还没加载到targetClasses，导致targetClasses.containsKey(cls.getName())无法找到对于class。
tomcat 9.0.95
jdk 1.8.0_411

**Comment by keecth** [comment]
解决方式目前是spi创建线程sleep，等待tomcat Catalina.start之后执行SPI操作

**Comment by veo** [comment]
感谢反馈并解决问题
