### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by Mayter** [veo/vagent#2]
自己编译的一直注入失败，是编译的时候缺少参数吗

为什么没有哥斯拉，其实想写入一个哥斯拉马

**Comment by veo** [comment]
是releases正常，你自己编译的注入失败吗？

没有哥斯拉，是因哥斯拉内存马兼容性的问题，所以干脆不用哥斯拉

**Comment by Mayter** [comment]
> 是releases正常，你自己编译的注入失败吗？
> 
> 没有哥斯拉，是因哥斯拉内存马兼容性的问题，所以干脆不用哥斯拉

嗯编译没问题  只有几个worning 但是注入失败，同样的环境你的可以注入成功

**Comment by veo** [comment]
你可以试试assembly打包方式，如果还不行那我也不知道为啥

**Comment by jielansudo** [comment]
我也遇到这个问题了，自己编译的发现不能正常注入，而且还导致后续在使用正常的，也不行了，必须要重启才能正常注入，想问问你怎么解决的。

**Comment by jielansudo** [comment]
我用 assembly package 打包一样的源码，也还是没办法注入，不知道为什么
